# Generated by Django 5.2.4 on 2025-07-19 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='project_description',
            new_name='portfolio_description',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='project_title',
            new_name='portfolio_title',
        ),
    ]
